services:
  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: bank_card_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  postgres:
    image: postgres:16.4
    container_name: bank_card_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bank_cards
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bank-rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_rest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://bank_card_postgres:5432/bank_cards
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      JWT_SECRET: a3K8Bx2Qm9Rt5Yw7Ez4Ns6Vp1Hj0Lg8Df6Cb3Xz9We2Yu5Tr8Mn4Kp7Jh0Bg5Nf
      JWT_EXPIRATION_TIME: 86400000
      CARD_ENCRYPTION_KEY: SecureCardKey1234567890123456789


volumes:
  postgres_data:
  pgadmin_data: