services:
  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: bank_card_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  postgres:
    image: postgres:16.4
    container_name: bank_card_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bank_cards
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  postgres_data:
  pgadmin_data: